---
abstract: 'Trim whitespace from all lines'
author:
  - 'Erik Carlsson <info@code301.com>'
build_requires: {}
configure_requires:
  Module::Build::Tiny: '0.039'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Syntax-Feature-Qs
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  B::Hooks::EndOfScope: '0.09'
  Devel::Declare: '0.006007'
  Devel::Declare::Context::Simple: '0'
  MooseX::Role::Parameterized: '1.00'
  Sub::Install: '0.925'
  Syntax::Feature::Simple::V2: '0'
  namespace::clean: '0'
  perl: '5.008005'
version: '0.0101'
